#' The iraceplot package: \packageTitle{iraceplot}
#'
#' \packageDescription{iraceplot}
#'
#' @name iraceplot-package
#' @docType package
#'
#' @details  License: MIT + file LICENSE
#'
#' @author Maintainers: Pablo Oñate Marín and Leslie Pérez Cáceres
#'         \email{pablo.onate.m@gmail.com}
#'
#' @keywords package plot automatic configuration
#'
#' @examples
#' ###########################################
#' # These examples illustrate how the various
#' # functions of the package works.
#' ###########################################
#'
#' # First we need to locate the data file generated by irace,
#' # which will be used for the various graphics
#'
#' load(location/file.Rdata)
#'
#' # Boxplot
#'
#' #
#'
#'
#'
NULL
