#' Create HTML Report from irace data
#' 
#' This function creates an HTML report of the most relevant irace data.  This
#' report provides general statistics and plots that show the best
#' configurations and their performance. Example: <https://auto-optimization.github.io/iraceplot/articles/example/report_example.html>
#'
#' @template arg_irace_results
#'
#' @param filename (`character(1)`)
#' Filename indicating where to save the report (example: `"~/path-to/filename"`)
#' @template arg_interactive
#'
#  Useless imports to suppress a NOTE generated by "R CMD check" 
#' @importFrom DT renderDataTable
#' @importFrom knitr knit
#' 
#' @examples
#' # load(system.file(package="irace", "exdata", "irace-acotsp.Rdata", mustWork = TRUE))
#' # report(iraceResults, filename="report")
#' NULL
#' @export
report <- function(irace_results, filename = "report",
                   interactive = base::interactive())
{
  if (missing(irace_results)) stop("irace_results is required")
  # FIXME: replace with irace::read_logfile
  irace_results <- read_logfile(irace_results)
 
  filename <- path_rel2abs(maybe_add_file_extension(filename, "html"))
  message("Creating file", filename, "\n")
  rmarkdown::render(input=system.file("template", "report_html.Rmd", package = "iraceplot"), output_file=filename)
  if (interactive) utils::browseURL(filename)
  filename
}
